[build]
publish = "public"
command = "./stackbit-build.sh"

[context.deploy-preview.environment]
  GATSBY_STACKBIT_API_URL = "https://dev-api.stackbit.com"
  GATSBY_STACKBIT_DEMO_URL = "https://demo.stackbit.com"

[context.branch-deploy.environment]
  GATSBY_STACKBIT_API_URL = "https://dev-api.stackbit.com"
  GATSBY_STACKBIT_DEMO_URL = "https://demo.stackbit.com"

[context.production.environment]
  GATSBY_STACKBIT_API_URL = "https://api.stackbit.com"
  GATSBY_STACKBIT_DEMO_URL = "https://demo.stackbit.com"

[context.staging.environment]
  GATSBY_STACKBIT_API_URL = "https://stg-api.stackbit.com"
  GATSBY_STACKBIT_DEMO_URL = "https://demo.stackbit.com"
